version: '3.8'
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/react
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    build: ./backend
    volumes:
      - ./backend:/rails
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/myapp_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    tty: true
    stdin_open: true
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp_development

volumes:
  postgres_data: